-- Confirmed walking route (entrance to exit), walk_order 1-25
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'DELI', '', 1);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'FRESH PRODUCE', '', 2);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'AB1', 'Bread/Bakery', 3);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A1', 'Fresh Vegetables', 4);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A2-A3', 'Waffles, Potatoes, Ice Cream, Frozen Breakfast', 5);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A4-A5', 'Frozen Pizza, Frozen Meals, Frozen Snacks', 6);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A6-A7', 'Candy, Frozen Vegetables', 7);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A8-A9', 'Pasta, Condiments, Canned Beans, Canned Vegetables', 8);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A10-A11', 'Soup, Rice & Beans, Canned Meat, International Foods', 9);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A12-A13', 'Spices, Baking, Shortening, Cake Mixes', 10);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A14-A15', 'Bread, Coffee, Snack Cakes, Canned Fruit', 11);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A16-A17', 'Granola & Snack Bars, Cereals, Syrup & Pancake Mix', 12);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A18-A19', 'Cookies, Popcorn, Crackers', 13);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A20-A21', 'Juice, Soft Drink', 14);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A22-A23', 'Trash Bags, Paper Goods, Paper Towels, Plastic Wraps', 15);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A24-A25', 'Insecticides, Mops & Brooms, Bathroom Tissue, All Purpose Cleaners', 16);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A26-A27', 'Bleach, Air Fresheners, Dish Detergent, Laundry', 17);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A28', 'Yogurt, Butter', 18);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A35, A29, A31, A33', 'Snacks, Chips, Pretzels, Beverages, Alcohol', 19);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A37', 'Milk, Creamer, Eggs, Juice', 20);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A39', 'Dairy, Cheese, Lunch', 21);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'AC3', 'Meats', 22);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A39', 'Breakfast, Poultry, Pork, Beef', 23);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'AC1', 'Meats', 24);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'A41', 'Seafood', 25);

-- Labeled, unordered (non-grocery departments) - walk_order left NULL
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'AUTO', '', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'I5', 'HOME', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), '', 'FURNITURE', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), '', 'LAUNDRY', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'H7', 'CRAFTS', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'E1 - E15', 'GIRLS', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'H1', 'ELECTRONICS', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), '', 'BEDDING', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), '', 'KITCHEN', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'H1 - H10', 'BATH & SHOWER', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'G1-G5', 'PHARMACY', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'E16 - E30', 'BOYS', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'D23 - D33', 'SHOES', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'GD1 - D25', 'MENS', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'G1 - G30', 'PERSONAL CARE', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'C15 - C25', 'BABY', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'B25 - B35', 'INTIMATES', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), '', 'ANIMAL PRODUCTS', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'C9 - C15', 'BABY', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'B1 - B13', '', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'B39-B47', 'WOMENS', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'B55 - B69', 'SHOES', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'B49 - B61', 'JEWELRY', NULL);
INSERT INTO aisle_directory (id, code, categories, walk_order) VALUES (lower(hex(randomblob(16))), 'B15-B37', 'WOMENS', NULL);
